services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Shop!
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
